linters:
  enable:
    - exportloopref # Checks for pointers to enclosing loop variables
    - gofmt
    - goimports
    - gosec
    - ineffassign
    - misspell
    - revive
    - staticcheck
    - structcheck
    - tenv # Detects using os.Setenv instead of t.Setenv since Go 1.17
    - unconvert
    - unused
    - varcheck
    - vet
  disable:
    - errcheck

issues:
  include:
    - EXC0002
  max-issues-per-linter: 0
  max-same-issues: 0

linters-settings:
  gosec:
    # The following issues surfaced when `gosec` linter
    # was enabled. They are temporarily excluded to unblock
    # the existing workflow, but still to be addressed by
    # by future works.
    excludes:
      - G204
      - G305
      - G306
      - G402
      - G404

run:
  timeout: 8m
  skip-dirs:
    - api
    - cluster
    - design
    - docs
    - docs/man
    - releases
    - reports
    - test # e2e scripts
