dist: trusty
sudo: required

language: go

go:
  - 1.8.x
  - tip

go_import_path: github.com/containerd/containerd

addons:
  apt:
    packages:
      - apparmor
      - libapparmor-dev
      - curl

env:
  - SECCOMP_VERSION=2.3.1 RUNC_COMMIT=b6b70e53451794e8333e9b602cc096b47a20bd0f


install:
  - hack/install-seccomp.sh
  - hack/install-runc.sh
  - go get -u github.com/golang/lint/golint

script:
  - make all
  - sudo make install
  - sudo -E env "PATH=$PATH" "GOPATH=$GOPATH" make test
  - sudo -E env "PATH=$PATH" "GOPATH=$GOPATH" make integration-test
