# commit to be tagged for new release
commit = "HEAD"

project_name = "containerd"
github_repo = "containerd/containerd"
match_deps = "^github.com/(containerd/[a-zA-Z0-9-]+)$"

# previous release
previous = "v1.1.7"

pre_release = false

preface = """\
This is the eight patch release for the `containerd` 1.1 release. This is the
first 1.1 release during the extended security release period. Included is
a runc fix for [CVE-2019-16884](https://nvd.nist.gov/vuln/detail/CVE-2019-16884)
as well as fixes to close inherited sockets and cleanup on context cancellation
in CRI.

Go version has also been updated to 1.12 in this release.

Please see the changelog for full details.
"""

# notable prs to include in the release notes, 1234 is the pr number
[notes]

[breaking]
