# commit to be tagged for new release
commit = "HEAD"

project_name = "containerd"
github_repo = "containerd/containerd"
match_deps = "^github.com/(containerd/[a-zA-Z0-9-]+)$"

# previous release
previous = "v1.3.6"

pre_release = false

preface = """\
The seventh patch release for `containerd` 1.3 includes bug fixes related to clean-up of containers that don't exist, and suspending a devmapper device to avoid data corruption when taking snapshots.

### Notable Updates

* Transfer error to ErrNotFound when kill a not exist container [containerd/containerd#4361](https://github.com/containerd/containerd/pull/4361)
* snapshots/devmapper: suspend a device to avoid data corruption [containerd/containerd#4416](https://github.com/containerd/containerd/pull/4416)
* shim: move event context timeout to publisher [containerd/containerd#4417](https://github.com/containerd/containerd/pull/4417)
* Allow empty scope authorization [containerd/containerd#4422](https://github.com/containerd/containerd/pull/4422)
* Replace ocispec.MediaTypeImageManifest with manifest.MediaType [containerd/containerd#4432](https://github.com/containerd/containerd/pull/4432)

"""

# notable prs to include in the release notes, 1234 is the pr number
[notes]

[breaking]
